#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "academic_library"
name = "Academic Library"
description.en = "Free academic books library with covers and metadata"

version = "2.0.0~ynh1"

maintainers = ["Citify"]

[upstream]
license = "MIT"
website = "https://github.com/Citify/academic_library_ynh"
code = "https://github.com/Citify/academic_library_ynh"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "1G"
ram.build = "512M"
ram.runtime = "256M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/library"

    [install.init_main_permission]
    help.en = "If public, anyone can access the library without logging in"
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "python3-venv, python3-pip, python3-dev, build-essential, libxml2-dev, libxslt1-dev"
